/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppContent: typeof import('./src/components/layout/AppContent.vue')['default']
    AppHeader: typeof import('./src/components/layout/AppHeader.vue')['default']
    BaseButton: typeof import('./src/components/common/BaseButton.vue')['default']
    BaseIcon: typeof import('./src/components/common/BaseIcon.vue')['default']
    BaseInput: typeof import('./src/components/common/BaseInput.vue')['default']
    BaseLoading: typeof import('./src/components/common/BaseLoading.vue')['default']
    ChatAvatar: typeof import('./src/components/chat/ChatAvatar.vue')['default']
    ChatInput: typeof import('./src/components/chat/ChatInput.vue')['default']
    ChatMessage: typeof import('./src/components/chat/ChatMessage.vue')['default']
    ChatMessageList: typeof import('./src/components/chat/ChatMessageList.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MarkdownRenderer: typeof import('./src/components/functional/MarkdownRenderer.vue')['default']
    MemorySection: typeof import('./src/components/functional/MemorySection.vue')['default']
    NAlert: typeof import('naive-ui')['NAlert']
    NButton: typeof import('naive-ui')['NButton']
    NDivider: typeof import('naive-ui')['NDivider']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NList: typeof import('naive-ui')['NList']
    NListItem: typeof import('naive-ui')['NListItem']
    NModal: typeof import('naive-ui')['NModal']
    NPopconfirm: typeof import('naive-ui')['NPopconfirm']
    NPopover: typeof import('naive-ui')['NPopover']
    NSelect: typeof import('naive-ui')['NSelect']
    NSlider: typeof import('naive-ui')['NSlider']
    NSpace: typeof import('naive-ui')['NSpace']
    NSpin: typeof import('naive-ui')['NSpin']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsPanel: typeof import('./src/components/functional/SettingsPanel.vue')['default']
    Sidebar: typeof import('./src/components/layout/Sidebar.vue')['default']
    Toast: typeof import('./src/components/functional/Toast.vue')['default']
  }
}
